# Arranged by ISO weekday, 1 (Monday) through 7 (Sunday) 

[1]
location = "Ezekiel 11:19"
verse = "I will give them a new heart and put a new spirit within them; I will remove the stony heart from their bodies, and replace it with a natural heart."

[2]
location = "Matthew 26:27-29"
verse = "Then he took a cup, gave thanks, and gave it to them, saying, \"Drink from it, all of you, for this is my blood of the covenant, which will be shed on behalf of many for the forgiveness of sins. I tell you, from now on, I shall not drink this fruit of the vine until the day when I drink it with you new in the kingdom of my Father\""

[3]
location = "Isaiah 43:18-19"
verse = "Remember not the events of the past, the things long ago consider not;\nSee I am doing something new! Now it springs forth, do you not perceive it? In the desert I make way, in the wasteland, rivers."

[4]
location = "Lamentations 3:22-23"
verse = "The favors of the LORD are not exhausted, his mercies are not spent; They are renewed each morning, so great is his faithfulness."

[5]
location = "Ephesians 4:22-24"
verse = "That you should put away the old self of your former way of life, corrupted through deceitful desires, and be renewed in the spirit of your minds, and put on the new self, created in God's way in righteousness and holiness of the truth"

[6]
location = "2 Corinthians 5:17"
verse = "So whoever is in Christ is a new creation: the old things have passed away; behold, new things have come."

[7]
location = "Psalm 40:3"
verse = "Drew me out of the pit of destruction, out of the mud of the swamp.\nSet my feet upon rock, steadied my steps."