# Arranged by ISO weekday, 1 (Monday) through 7 (Sunday) 

[1]
location = "Ezekiel 11:19"
verse = "I will give them a new heart and put a new spirit within them; I will remove the stony heart from their bodies, and replace it with a natural heart."

[2]
location = "Matthew 26:27-29"
verse = "Then he took a cup, gave thanks, and gave it to them, saying, \"Drink from it, all of you, for this is my blood of the covenant, which will be shed on behalf of many for the forgiveness of sins. I tell you, from now on, I shall not drink this fruit of the vine until the day when I drink it with you new in the kingdom of my Father\""

[3]
location = "Isaiah 65:17"
verse = "Lo, I am about to create new heavens and a new earth; The things of the past shall not be remembered or come to mind."

[4]
location = "Romans 6:4"
verse = "We were indeed buried with him through baptism into death, so that, just as Christ was raised from the dead by the glory of the Father, we too may live in newness of life."

[5]
location = "Colossians 3:9-10"
verse = "Stop lying to one another, since you have taken off the old self with its practices and have put on the new self, which is being renewed, for knowledge, in the image of its creator."

[6]
location = "Revelation 21:5"
verse = "The rest of the dead did not come to life until the thousand years were over. This is the first resurrection."

[7]
location = "Psalm 40:3"
verse = "Drew me out of the pit of destruction, out of the mud of the swamp.\nSet my feet upon rock, steadied my steps."