[1]
location = "Job 8:7"
verse = "Your former state will be of little moment; for in time to come you will flourish indeed"

[2]
location = "Philippians 3:13-14"
verse = "Brothers, I for my part do not consider myself to have taken possession. Just one thing: forgetting what lies behind but straining forward to what lies ahead.\nI continue my pursuit toward the goal, the prize of God's upward calling, in Christ Jesus"

[3]
location = "Isaiah 43:18-19"
verse = "Remember not the events of the past, the things long ago consider not;\nSee I am doing something new! Now it springs forth, do you not perceive it? In the desert I make way, in the wasteland, rivers."

[4]
location = "Lamentations 3:22-23"
verse = "The favors of the LORD are not exhausted, his mercies are not spent; They are renewed each morning, so great is his faithfulness."

[5]
location = "Ephesians 4:22-24"
verse = "That you should put away the old self of your former way of life, corrupted through deceitful desires, and be renewed in the spirit of your minds, and put on the new self, created in God's way in righteousness and holiness of the truth"

[6]
location = "TBA"
verse = "TBA"

[7]
location = "Jeremiah 29:11"
verse = "and said in the presence of all the people: \"Thus says the LORD: \'Even so, within two years I will break the yoke of Nebuchadnezzar, king of Babylon, from off the neck of all the nations.\' \" At that, the prophet Jeremiah went away"
